name: flutter_workshop_front
description: "Flutter Workshop Frontend"
publish_to: 'none'

version: 1.3.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.5
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  go_router: ^14.3.0
  intl: any
  calendar_date_picker2: ^1.1.8
  shimmer: ^3.0.0
  collection: ^1.19.1
  provider: ^6.1.5
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^10.0.0
  package_info_plus: ^9.0.0
  device_info_plus: ^12.3.0
  jwt_decoder: ^2.0.1
  uuid: ^4.5.2
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/
  # fonts:

